/* This file is generated by npm run client:generate. Do not edit by hand. */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service capability document */
        get: operations["getRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 503 when `GNEWS_API_KEY` is not configured (non-test environments).
         */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI contract */
        get: operations["getOpenApiYaml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search articles with response metadata */
        get: operations["searchArticlesV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alias for v1 article search */
        get: operations["searchArticlesV1Alias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/title/{title}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find article by exact title with response metadata */
        get: operations["getArticleByTitleV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter articles by news source name with response metadata */
        get: operations["listArticlesBySourceV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search articles */
        get: operations["searchArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/title/{title}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find article by exact title */
        get: operations["getArticleByTitle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter articles by news source name */
        get: operations["listArticlesBySource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            error: string;
        };
        ErrorEnvelope: {
            error: {
                /** @example missing_query_parameter */
                code: string;
                /** @example Missing or empty query parameter: query */
                message: string;
                requestId: string;
            };
        };
        RootCapabilities: {
            /** @example news-api */
            name: string;
            api: {
                /** @example v1 */
                current: string;
                v1: {
                    [key: string]: string;
                };
                legacy: {
                    [key: string]: string;
                };
            };
            docs: {
                [key: string]: string;
            };
            observability: {
                [key: string]: string;
            };
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            /** Format: double */
            uptime: number;
        };
        ReadyResponse: {
            /** @example ready */
            status: string;
        };
        NotReadyResponse: {
            /** @example not_ready */
            status: string;
            /** @example missing_api_key */
            reason: string;
        };
        ArticleSource: {
            name: string;
            url: string;
        };
        Article: {
            title: string;
            description?: string | null;
            content?: string | null;
            url: string;
            image?: string | null;
            /** Format: date-time */
            publishedAt: string;
            source: components["schemas"]["ArticleSource"];
        };
        ArticleSearchMeta: {
            query: string;
            count: number;
            filters: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            cache: "hit" | "miss" | "coalesced" | "stale";
            requestId: string;
        };
        ArticleSearchEnvelope: {
            data: components["schemas"]["Article"][];
            meta: components["schemas"]["ArticleSearchMeta"];
        };
        ArticleEnvelope: {
            data: components["schemas"]["Article"];
            meta: {
                title?: string;
                requestId: string;
            };
        };
        SourceArticlesEnvelope: {
            data: components["schemas"]["Article"][];
            meta: {
                source: string;
                count: number;
                filters: {
                    [key: string]: unknown;
                };
                requestId: string;
            };
        };
    };
    responses: {
        /** @description Missing or invalid X-API-Key when CLIENT_API_KEYS is configured */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Invalid or missing parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Upstream provider error or invalid provider payload */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Unexpected server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Missing or invalid X-API-Key when CLIENT_API_KEYS is configured */
        V1Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Invalid or missing parameters */
        V1BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Upstream provider error or invalid provider payload */
        V1BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Unexpected server error */
        V1InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Upstream provider circuit breaker is open */
        V1ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Required when the server sets CLIENT_API_KEYS. */
        ClientApiKey: string;
        Query: string;
        Count: number;
        /** @description Two-letter article language code. */
        Lang: string;
        /** @description Two-letter source country code. */
        Country: string;
        /** @description Include articles published at or after this ISO 8601 timestamp. */
        From: string;
        /** @description Include articles published at or before this ISO 8601 timestamp. */
        To: string;
        /** @description Provider sort order. Forwarded to GNews as `sortby`. */
        SortBy: "publishedAt" | "relevance";
    };
    requestBodies: never;
    headers: {
        /** @description Version of the stable response envelope contract. */
        ApiVersion: "v1";
        /** @description Article-search cache result for this response. */
        CacheStatus: "hit" | "miss" | "stale";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Links to API versions, docs, and observability endpoints */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootCapabilities"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve traffic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Not ready (e.g. missing API key) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotReadyResponse"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text / OpenMetrics exposition format */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getOpenApiYaml: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3 document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    searchArticlesV1: {
        parameters: {
            query: {
                query: components["parameters"]["Query"];
                count?: components["parameters"]["Count"];
                /** @description Two-letter article language code. */
                lang?: components["parameters"]["Lang"];
                /** @description Two-letter source country code. */
                country?: components["parameters"]["Country"];
                /** @description Include articles published at or after this ISO 8601 timestamp. */
                from?: components["parameters"]["From"];
                /** @description Include articles published at or before this ISO 8601 timestamp. */
                to?: components["parameters"]["To"];
                /** @description Provider sort order. Forwarded to GNews as `sortby`. */
                sortBy?: components["parameters"]["SortBy"];
            };
            header?: {
                /** @description Required when the server sets CLIENT_API_KEYS. */
                "X-API-Key"?: components["parameters"]["ClientApiKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enveloped article list from provider (possibly cached) */
            200: {
                headers: {
                    "X-API-Version": components["headers"]["ApiVersion"];
                    "X-Cache-Status": components["headers"]["CacheStatus"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleSearchEnvelope"];
                };
            };
            400: components["responses"]["V1BadRequest"];
            401: components["responses"]["V1Unauthorized"];
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["V1InternalError"];
            502: components["responses"]["V1BadGateway"];
            503: components["responses"]["V1ServiceUnavailable"];
        };
    };
    searchArticlesV1Alias: {
        parameters: {
            query: {
                query: components["parameters"]["Query"];
                count?: components["parameters"]["Count"];
                /** @description Two-letter article language code. */
                lang?: components["parameters"]["Lang"];
                /** @description Two-letter source country code. */
                country?: components["parameters"]["Country"];
                /** @description Include articles published at or after this ISO 8601 timestamp. */
                from?: components["parameters"]["From"];
                /** @description Include articles published at or before this ISO 8601 timestamp. */
                to?: components["parameters"]["To"];
                /** @description Provider sort order. Forwarded to GNews as `sortby`. */
                sortBy?: components["parameters"]["SortBy"];
            };
            header?: {
                /** @description Required when the server sets CLIENT_API_KEYS. */
                "X-API-Key"?: components["parameters"]["ClientApiKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enveloped article list from provider (possibly cached) */
            200: {
                headers: {
                    "X-API-Version": components["headers"]["ApiVersion"];
                    "X-Cache-Status": components["headers"]["CacheStatus"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleSearchEnvelope"];
                };
            };
            400: components["responses"]["V1BadRequest"];
            401: components["responses"]["V1Unauthorized"];
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["V1InternalError"];
            502: components["responses"]["V1BadGateway"];
            503: components["responses"]["V1ServiceUnavailable"];
        };
    };
    getArticleByTitleV1: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the server sets CLIENT_API_KEYS. */
                "X-API-Key"?: components["parameters"]["ClientApiKey"];
            };
            path: {
                title: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enveloped matching article */
            200: {
                headers: {
                    "X-API-Version": components["headers"]["ApiVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleEnvelope"];
                };
            };
            401: components["responses"]["V1Unauthorized"];
            /** @description No article with that title in the search window */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["V1InternalError"];
            502: components["responses"]["V1BadGateway"];
            503: components["responses"]["V1ServiceUnavailable"];
        };
    };
    listArticlesBySourceV1: {
        parameters: {
            query?: {
                count?: components["parameters"]["Count"];
                /** @description Two-letter article language code. */
                lang?: components["parameters"]["Lang"];
                /** @description Two-letter source country code. */
                country?: components["parameters"]["Country"];
                /** @description Include articles published at or after this ISO 8601 timestamp. */
                from?: components["parameters"]["From"];
                /** @description Include articles published at or before this ISO 8601 timestamp. */
                to?: components["parameters"]["To"];
                /** @description Provider sort order. Forwarded to GNews as `sortby`. */
                sortBy?: components["parameters"]["SortBy"];
            };
            header?: {
                /** @description Required when the server sets CLIENT_API_KEYS. */
                "X-API-Key"?: components["parameters"]["ClientApiKey"];
            };
            path: {
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enveloped articles whose source name matches (case-insensitive) */
            200: {
                headers: {
                    "X-API-Version": components["headers"]["ApiVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceArticlesEnvelope"];
                };
            };
            400: components["responses"]["V1BadRequest"];
            401: components["responses"]["V1Unauthorized"];
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["V1InternalError"];
            502: components["responses"]["V1BadGateway"];
            503: components["responses"]["V1ServiceUnavailable"];
        };
    };
    searchArticles: {
        parameters: {
            query: {
                query: string;
                count?: number;
                /** @description Two-letter article language code. */
                lang?: string;
                /** @description Two-letter source country code. */
                country?: string;
                /** @description Include articles published at or after this ISO 8601 timestamp. */
                from?: string;
                /** @description Include articles published at or before this ISO 8601 timestamp. */
                to?: string;
                /** @description Provider sort order. Forwarded to GNews as `sortby`. */
                sortBy?: "publishedAt" | "relevance";
            };
            header?: {
                /** @description Required when the server sets CLIENT_API_KEYS. */
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article list from provider (possibly cached) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
            /** @description Upstream provider circuit breaker is open */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getArticleByTitle: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the server sets CLIENT_API_KEYS. */
                "X-API-Key"?: string;
            };
            path: {
                title: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching article */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description No article with that title in the search window */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
            /** @description Upstream provider circuit breaker is open */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listArticlesBySource: {
        parameters: {
            query: {
                source: string;
                count?: number;
                /** @description Two-letter article language code. */
                lang?: string;
                /** @description Two-letter source country code. */
                country?: string;
                /** @description Include articles published at or after this ISO 8601 timestamp. */
                from?: string;
                /** @description Include articles published at or before this ISO 8601 timestamp. */
                to?: string;
                /** @description Provider sort order. Forwarded to GNews as `sortby`. */
                sortBy?: "publishedAt" | "relevance";
            };
            header?: {
                /** @description Required when the server sets CLIENT_API_KEYS. */
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Articles whose source name matches (case-insensitive) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
            /** @description Upstream provider circuit breaker is open */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
